#!/usr/bin/env bash
#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# ~/.osx - http://mths.be/osx with macports and brew setup
#
# Authors:
#   Mathias Bynens
#   Ben O'Hara <bohara@gmail.com>
#

echo "WARNING: This could change settings you dont want, read it before running!"
echo -n "OK? (type 'yes'): "
read agree
if [[ $agree != 'yes' ]]; then
  echo "Bailing!"
  exit 1
fi

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
# General UI/UX                                                               #
###############################################################################

# Disable the “Are you sure you want to open this application?” dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Automatically illuminate built-in MacBook keyboard in low light
defaults write com.apple.BezelServices kDim -bool true

# Turn off keyboard illumination when computer is not used for 5 minutes
defaults write com.apple.BezelServices kDimTime -int 300

###############################################################################
# Terminal & iTerm 2                                                          #
###############################################################################

# Only use UTF-8 in Terminal.app
defaults write com.apple.terminal StringEncodings -array 4

# Use a modified version of the Pro theme by default in Terminal.app
#open "${HOME}/init/Mathias.terminal"
#sleep 1 # Wait a bit to make sure the theme is loaded
#defaults write com.apple.terminal "Default Window Settings" -string "Mathias"
#defaults write com.apple.terminal "Startup Window Settings" -string "Mathias"

# Enable “focus follows mouse” for Terminal.app and all X11 apps
# i.e. hover over a window and start typing in it without clicking first
#defaults write com.apple.terminal FocusFollowsMouse -bool true
#defaults write org.x.X11 wm_ffm -bool true

# Install pretty iTerm colors
open "${HOME}/${DOTFILES}/deploy/terminal/iterm2/dotphiles.itermcolors"

# Don’t display the annoying prompt when quitting iTerm
#defaults write com.googlecode.iterm2 PromptOnQuit -bool false

###############################################################################
# Time Machine                                                                #
###############################################################################

# Prevent Time Machine from prompting to use new hard drives as backup volume
#defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Disable local Time Machine backups
#hash tmutil &> /dev/null && sudo tmutil disablelocal

###############################################################################
# Homebrew
###############################################################################

if [[ -f $DIR/packages/homebrew ]]; then
  exec<$DIR/packages/homebrew
  while read line
  do
    if [[ ! "$line" =~ (^#|^$) ]]; then
      brew install $line
    fi
  done
fi

echo "Done. Note that some of these changes require a logout/restart to take effect."

